# Usa la imagen oficial de Python 3.10 como base
FROM python:3.10

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    default-jre-headless \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Establecer la variable de entorno JAVA_HOME para H2O
ENV JAVA_HOME=/usr/lib/jvm/default-java

RUN pip install --no-cache-dir --upgrade pip setuptools
RUN pip install --no-cache-dir h2o==3.46.0.4 pandas==2.2.2 scikit-learn==1.5.1 matplotlib

WORKDIR /comparison
COPY H2O.py /comparison/H2O.py

ENTRYPOINT ["python", "H2O.py"]


